FROM --platform=linux/arm64/v8 debian:bookworm AS rpi-sysroot

ENV DEBIAN_FRONTEND='noninteractive'

RUN apt update && \
    apt install -y --no-install-recommends apt-utils && \
    apt install -y wget gnupg \
    && rm -rf /var/lib/apt/lists/*

RUN wget -O- http://archive.raspberrypi.org/debian/raspberrypi.gpg.key | \
    gpg --dearmor | tee /etc/apt/keyrings/raspberrypi.gpg > /dev/null \
    && chmod 644 /etc/apt/keyrings/raspberrypi.gpg \
    && echo "deb [signed-by=/etc/apt/keyrings/raspberrypi.gpg] http://archive.raspberrypi.org/debian/ bookworm main" >> /etc/apt/sources.list \
    && sed -i '/^Types:/ s/\<deb\>\(.*\)\(\<deb-src\>\)\?/\0 deb-src/' /etc/apt/sources.list.d/debian.sources \
    && apt update

RUN apt install -y \
		libfontconfig1-dev libdbus-1-dev libfreetype6-dev libicu-dev libinput-dev libxkbcommon-dev libsqlite3-dev libssl-dev libpng-dev libjpeg-dev libglib2.0-dev libgles2-mesa-dev libgbm-dev libdrm-dev libx11-dev libxcb1-dev libxext-dev libxi-dev libxcomposite-dev libxcursor-dev libxtst-dev libxrandr-dev libx11-xcb-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-util0-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libxcb-xinput-dev libxcb-cursor-dev libatspi2.0-dev pigpio \
	&& dpkg --purge libraspberrypi-dev \
	&& apt-get autoremove --purge -y \
    && apt clean -y \
    && rm -rf /var/lib/apt/lists/*

